import { refreshClineRulesToggles } from "@core/context/instructions/user-instructions/cline-rules"
import { removeGeneratedContextFolderRules } from "@core/context/instructions/user-instructions/context-folders"
import { refreshExternalRulesToggles } from "@core/context/instructions/user-instructions/external-rules"
import { estimateRuleFileTokens } from "@core/context/instructions/user-instructions/instruction-tokens"
import { refreshWorkflowToggles } from "@core/context/instructions/user-instructions/workflows"
import { EmptyRequest } from "@shared/proto/cline/common"
import { RefreshedRules } from "@shared/proto/cline/file"
import { Logger } from "@/shared/services/Logger"
import { getCwd, getDesktopDir } from "@/utils/path"
import type { Controller } from "../index"

/**
 * Refreshes all rule toggles (Cline, External, and Workflows)
 * @param controller The controller instance
 * @param _request The empty request
 * @returns RefreshedRules containing updated toggles for all rule types
 */
export async function refreshRules(controller: Controller, _request: EmptyRequest): Promise<RefreshedRules> {
	try {
		const cwd = await getCwd(getDesktopDir())

		// Delete rule files generated by the removed context-folder import
		// before the cline-rules scanner would pick them up again.
		await removeGeneratedContextFolderRules(controller, cwd)

		const { globalToggles, localToggles } = await refreshClineRulesToggles(controller, cwd)
		const { cursorLocalToggles, windsurfLocalToggles, agentsLocalToggles, copilotLocalToggles } =
			await refreshExternalRulesToggles(controller, cwd)
		const { localWorkflowToggles, globalWorkflowToggles } = await refreshWorkflowToggles(controller, cwd)

		const tokenCounts = await estimateRuleFileTokens([
			globalToggles,
			localToggles,
			cursorLocalToggles,
			windsurfLocalToggles,
			agentsLocalToggles,
			copilotLocalToggles,
		])

		return RefreshedRules.create({
			globalClineRulesToggles: { toggles: globalToggles },
			localClineRulesToggles: { toggles: localToggles },
			localCursorRulesToggles: { toggles: cursorLocalToggles },
			localWindsurfRulesToggles: { toggles: windsurfLocalToggles },
			localAgentsRulesToggles: { toggles: agentsLocalToggles },
			localCopilotRulesToggles: { toggles: copilotLocalToggles },
			localWorkflowToggles: { toggles: localWorkflowToggles },
			globalWorkflowToggles: { toggles: globalWorkflowToggles },
			tokenCounts,
		})
	} catch (error) {
		Logger.error("Failed to refresh rules:", error)
		throw error
	}
}
