/** Auto-generated by scripts/generate-models.ts. Do not edit manually. */
/** PlinyCode override: only Pliny gateway models — never Cline cloud recommended. */
import type { ClineRecommendedModelsPayload } from "./catalog-cline-recommended";

export const GENERATED_CLINE_RECOMMENDED_MODELS: ClineRecommendedModelsPayload =
	{
		recommended: [
			{
				id: "snps-aws-bedrock/aws-claude-sonnet-4.6",
				name: "Claude Sonnet 4.6",
				description: "Default hosted coder via Pliny (Bedrock)",
				tags: ["DEFAULT"],
			},
			{
				id: "snps-aws-bedrock/global.anthropic.claude-sonnet-5",
				name: "Claude Sonnet 5",
				description:
					"Strongest hosted coder on Pliny; supports prompt caching",
				tags: ["HOSTED"],
			},
			{
				id: "snps-provider/GLM-5.2",
				name: "GLM-5.2",
				description: "Largest self-hosted context (512k) via Pliny",
				tags: ["SELF-HOSTED"],
			},
			{
				id: "snps-provider/qwen3-coder-480b-a35b-inst-fp8",
				name: "Qwen3 Coder 480B",
				description: "Coding-specialised self-hosted model",
				tags: ["SELF-HOSTED"],
			},
			{
				id: "snps-provider/kimi-k2.6",
				name: "Kimi K2.6",
				description: "Large self-hosted MoE via Pliny",
				tags: ["SELF-HOSTED"],
			},
			{
				id: "azure-openai/gpt-5.2",
				name: "GPT-5.2",
				description: "Hosted via Pliny Azure OpenAI (auto-caches)",
				tags: ["HOSTED"],
			},
		],
		free: [],
		clinePass: [],
	};
