import { ClineRulesToggles } from "@shared/cline-rules"
import fs from "fs/promises"
import path from "path"
import type { Controller } from "@/core/controller"

/** Prefix and header of the rule files the removed context-folder import generated. */
const GENERATED_PREFIX = "pliny-context-"
const GENERATED_HEADER = "# Context from "

/**
 * Remove the `.cline/rules/pliny-context-*.md` files that earlier versions
 * generated by concatenating `.github`, `.vscode`, `.devcontainer` and
 * `.cursor` into single rules. The SDK loads every file in `.cline/rules`, so
 * these dumps reached the model even while the Rules panel showed them as
 * disabled. Rules from other agents are now read in place (see
 * external-rules.ts), so the generated copies are deleted, together with the
 * `.cline/rules` and `.cline` directories if nothing else lives there.
 *
 * Only files that still start with the generated header are removed, so a user
 * file that happens to share the prefix is left alone.
 */
export async function removeGeneratedContextFolderRules(controller: Controller, workingDirectory: string): Promise<void> {
	const clineDir = path.join(workingDirectory, ".cline")
	const rulesDir = path.join(clineDir, "rules")

	let entries: string[]
	try {
		entries = await fs.readdir(rulesDir)
	} catch {
		return
	}

	const localToggles: ClineRulesToggles = controller.stateManager.getWorkspaceStateKey("localClineRulesToggles") ?? {}
	let removedAny = false
	for (const entry of entries) {
		if (!entry.startsWith(GENERATED_PREFIX) || !entry.endsWith(".md")) {
			continue
		}
		const filePath = path.join(rulesDir, entry)
		try {
			const content = await fs.readFile(filePath, "utf-8")
			if (!content.startsWith(GENERATED_HEADER)) {
				continue
			}
			await fs.unlink(filePath)
			delete localToggles[filePath]
			removedAny = true
		} catch {
			// Unreadable or already gone: nothing to clean up.
		}
	}

	if (!removedAny) {
		return
	}
	controller.stateManager.setWorkspaceState("localClineRulesToggles", localToggles)

	// rmdir only succeeds on empty directories, so anything the user keeps there survives.
	await fs.rmdir(rulesDir).catch(() => {})
	await fs.rmdir(clineDir).catch(() => {})
}
